# Generated by Django 3.1.7 on 2021-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=511)),
                ('last_name', models.CharField(max_length=511)),
                ('email', models.CharField(max_length=511)),
                ('address', models.CharField(max_length=16000)),
                ('birthdate', models.DateField()),
                ('authenticated', models.BooleanField(default=False)),
                ('profile_pic', models.CharField(max_length=16000)),
            ],
        ),
    ]
