# Generated by Django 2.1.5 on 2021-05-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, max_length=16000)),
                ('date_arrived', models.DateTimeField(auto_now_add=True)),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Citizen', to_field='citizen_id')),
            ],
        ),
    ]
